spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:D:/Projects/REPORTVENTAS/ventas.db
    
  jackson:
    default-property-inclusion: non_absent
    
  jpa:
    show-sql: true
    properties:
       hibernate:
          dialect: org.hibernate.dialect.SQLiteDialect
          format_sql: true
      